import { pgTable, text, integer, real, timestamp, index } from "drizzle-orm/pg-core";
import { categories } from "./categories";

export const products = pgTable("products", {
  id: text("id").primaryKey(),
  code: text("code").unique(),
  sku: text("sku").unique(),
  barcode: text("barcode"),
  name: text("name").notNull(),
  nameAr: text("name_ar"),
  description: text("description"),
  categoryId: text("category_id").references(() => categories.id),
  brand: text("brand"),
  model: text("model"),
  specs: text("specs"),
  costPrice: real("cost_price"),
  costPriceEncrypted: text("cost_price_encrypted"),
  sellingPrice: real("selling_price"),
  wholesalePrice: real("wholesale_price"),
  minPrice: real("min_price"),
  trackBySerial: integer("track_by_serial").default(0),
  quantity: integer("quantity").default(0),
  minQuantity: integer("min_quantity").default(0),
  maxQuantity: integer("max_quantity"),
  unit: text("unit").default("piece"),
  warrantyMonths: integer("warranty_months").default(0),
  isActive: integer("is_active").default(1),
  isFeatured: integer("is_featured").default(0),
  isArchived: integer("is_archived").default(0),
  images: text("images"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  createdBy: text("created_by"),
  isDeleted: integer("is_deleted").default(0),
  deletedAt: timestamp("deleted_at"),
}, (table) => [
  index("products_category_id_idx").on(table.categoryId),
  index("products_created_by_idx").on(table.createdBy),
  index("products_is_active_idx").on(table.isActive),
  index("products_is_archived_idx").on(table.isArchived),
  index("products_is_deleted_idx").on(table.isDeleted),
  index("products_created_at_idx").on(table.createdAt),
]);
