import { pgTable, text, integer, real, timestamp, index } from "drizzle-orm/pg-core";

export const suppliers = pgTable("suppliers", {
  id: text("id").primaryKey(),
  code: text("code").unique(),
  name: text("name").notNull(),
  nameAr: text("name_ar"),
  type: text("type").default("company"),
  contactPerson: text("contact_person"),
  phone: text("phone"),
  phone2: text("phone2"),
  email: text("email"),
  website: text("website"),
  address: text("address"),
  city: text("city"),
  country: text("country"),
  defaultWarrantyMonths: integer("default_warranty_months").default(0),
  warrantyTerms: text("warranty_terms"),
  balance: real("balance").default(0),
  creditLimit: real("credit_limit").default(0),
  paymentTerms: text("payment_terms"),
  taxNumber: text("tax_number"),
  rating: real("rating").default(0),
  totalPurchases: real("total_purchases").default(0),
  notes: text("notes"),
  tags: text("tags"),
  isActive: integer("is_active").default(1),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  isDeleted: integer("is_deleted").default(0),
  deletedAt: timestamp("deleted_at"),
}, (table) => [
  index("suppliers_is_active_idx").on(table.isActive),
  index("suppliers_is_deleted_idx").on(table.isDeleted),
  index("suppliers_created_at_idx").on(table.createdAt),
]);
