/**
 * تصنيفات المنتجات - 28 تصنيف
 * من نظام المربع
 */

export const CATEGORIES = [
  { id: "cat_1", code: "GEN", name: "General", nameAr: "عامة", sortOrder: 1 },
  { id: "cat_2", code: "LAPTOP_USED", name: "Used Laptops", nameAr: "لابتوب باله", sortOrder: 2 },
  { id: "cat_3", code: "ACTIVATIONS", name: "Software Activations", nameAr: "تفعيلات", sortOrder: 3 },
  { id: "cat_4", code: "MOUSE", name: "Mouse", nameAr: "ماوس", sortOrder: 4 },
  { id: "cat_5", code: "JOYSTICK", name: "Joystick", nameAr: "جوستك", sortOrder: 5 },
  { id: "cat_6", code: "PC_ACC", name: "Computer Accessories", nameAr: "اكسسوارات الحاسوب", sortOrder: 6 },
  { id: "cat_7", code: "CAMERA", name: "Cameras & Accessories", nameAr: "كامرات + ملحقاتها", sortOrder: 7 },
  { id: "cat_8", code: "INTERNET", name: "Internet Devices", nameAr: "الانترنت", sortOrder: 8 },
  { id: "cat_9", code: "MOBILE_CABLE", name: "Mobile Cables", nameAr: "كيبل موبايل", sortOrder: 9 },
  { id: "cat_10", code: "MOBILE_CHARGER", name: "Mobile Chargers", nameAr: "شواحن موبايل", sortOrder: 10 },
  { id: "cat_11", code: "MOBILE_EARPHONE", name: "Mobile Earphones", nameAr: "سماعه موبايل", sortOrder: 11 },
  { id: "cat_12", code: "PC_MON", name: "PC + Monitor", nameAr: "pc+mon", sortOrder: 12 },
  { id: "cat_13", code: "SECURITY_CAM", name: "Security Cameras", nameAr: "كاميرات مراقبه", sortOrder: 13 },
  { id: "cat_14", code: "SPEAKER_MIC", name: "Speakers & Microphones", nameAr: "سبيكر + مايك", sortOrder: 14 },
  { id: "cat_15", code: "PRINTER", name: "Printers & Accessories", nameAr: "طابعات + ملحقاتها", sortOrder: 15 },
  { id: "cat_16", code: "LAPTOP_NEW", name: "New Laptops", nameAr: "لابتوب جديد", sortOrder: 16 },
  { id: "cat_17", code: "BAGS", name: "Bags", nameAr: "حقائب", sortOrder: 17 },
  { id: "cat_18", code: "LAPTOP_REFURB", name: "Refurbished Laptops", nameAr: "لابتوب مستخدم", sortOrder: 18 },
  { id: "cat_19", code: "SERVICES", name: "Services", nameAr: "اجور", sortOrder: 19 },
  { id: "cat_20", code: "LAPTOP_CHARGER", name: "Laptop Chargers", nameAr: "شواحن لابتوب", sortOrder: 20 },
  { id: "cat_21", code: "MOUSE_PAD", name: "Mouse Pads", nameAr: "باد ماوس", sortOrder: 21 },
  { id: "cat_22", code: "STYLUS", name: "Stylus Pens", nameAr: "اقلام", sortOrder: 22 },
  { id: "cat_23", code: "WATCHES", name: "Smart Watches", nameAr: "ساعات", sortOrder: 23 },
  { id: "cat_24", code: "MOBILE", name: "Mobile Phones", nameAr: "موبايل", sortOrder: 24 },
  { id: "cat_25", code: "MOBILE_ACC", name: "Mobile Accessories", nameAr: "ملحقات الموبايل", sortOrder: 25 },
  { id: "cat_26", code: "MORABAA", name: "Morabaa Items", nameAr: "المربع", sortOrder: 26 },
  { id: "cat_27", code: "TABLET", name: "Tablets", nameAr: "تابلت", sortOrder: 27 },
  { id: "cat_28", code: "TABLET_KB", name: "Tablet Keyboards", nameAr: "كيبورد تابلت", sortOrder: 28 },
];

// تحويل group_id القديم لـ category_id الجديد
export const GROUP_TO_CATEGORY: Record<number, string> = {
  1: "cat_1",
  2: "cat_2",
  3: "cat_3",
  4: "cat_4",
  5: "cat_5",
  6: "cat_6",
  7: "cat_7",
  8: "cat_8",
  9: "cat_9",
  10: "cat_10",
  11: "cat_11",
  12: "cat_12",
  13: "cat_13",
  14: "cat_14",
  15: "cat_15",
  16: "cat_16",
  17: "cat_17",
  18: "cat_18",
  19: "cat_19",
  20: "cat_20",
  21: "cat_21",
  22: "cat_22",
  23: "cat_23",
  24: "cat_24",
  25: "cat_25",
  26: "cat_26",
  27: "cat_27",
  28: "cat_28",
};
