/**
 * بيانات شركة BI للحاسبات
 * الأقسام + المناصب + الموظفين + معلومات الشركة
 */

// ==================== الأقسام ====================
export const DEPARTMENTS = [
  {
    id: "dept_preparation",
    code: "PREP",
    name: "Preparation & Installation",
    nameAr: "التجهيز والتنصيب",
    isActive: 1,
  },
  {
    id: "dept_support",
    code: "SUPPORT",
    name: "Technical Support",
    nameAr: "الدعم الفني",
    isActive: 1,
  },
  {
    id: "dept_media",
    code: "MEDIA",
    name: "Photography & Marketing",
    nameAr: "التصوير والتسويق",
    isActive: 1,
  },
  {
    id: "dept_sales",
    code: "SALES",
    name: "Sales & Customer Service",
    nameAr: "المبيعات والردود",
    isActive: 1,
  },
  {
    id: "dept_maintenance",
    code: "MAINT",
    name: "Maintenance",
    nameAr: "الصيانة",
    isActive: 1,
  },
  {
    id: "dept_programming",
    code: "DEV",
    name: "Programming",
    nameAr: "البرمجيات",
    isActive: 1,
  },
  {
    id: "dept_design",
    code: "DESIGN",
    name: "Design",
    nameAr: "التصميم",
    isActive: 1,
  },
  {
    id: "dept_services",
    code: "SVC",
    name: "Services",
    nameAr: "الخدمات",
    isActive: 1,
  },
];

// ==================== المناصب ====================
export const POSITIONS = [
  { id: "pos_owner", code: "OWNER", name: "Owner", nameAr: "المالك", departmentId: null, level: 10 },
  { id: "pos_ceo", code: "CEO", name: "Executive Director", nameAr: "المدير التنفيذي", departmentId: null, level: 9 },
  { id: "pos_prep", code: "PREP", name: "Laptop Preparer", nameAr: "مجهز لابتوبات", departmentId: "dept_preparation", level: 3 },
  { id: "pos_installer", code: "INST", name: "Installer", nameAr: "تنصيب وتجهيز", departmentId: "dept_preparation", level: 3 },
  { id: "pos_tech_support", code: "TSUP", name: "Technical Support", nameAr: "دعم فني", departmentId: "dept_support", level: 3 },
  { id: "pos_photographer", code: "PHOTO", name: "Photographer", nameAr: "مصور", departmentId: "dept_media", level: 3 },
  { id: "pos_editor", code: "EDIT", name: "Video Editor", nameAr: "مونتير", departmentId: "dept_media", level: 3 },
  { id: "pos_sales", code: "SALES", name: "Sales Representative", nameAr: "موظف مبيعات", departmentId: "dept_sales", level: 3 },
  { id: "pos_maintenance", code: "MAINT", name: "Maintenance Technician", nameAr: "فني صيانة", departmentId: "dept_maintenance", level: 3 },
  { id: "pos_programmer", code: "DEV", name: "Programmer", nameAr: "مبرمج", departmentId: "dept_programming", level: 4 },
  { id: "pos_designer", code: "DSGN", name: "Graphic Designer", nameAr: "مصمم جرافيك", departmentId: "dept_design", level: 3 },
  { id: "pos_marketing", code: "MKT", name: "Marketing Manager", nameAr: "مسؤول ماركتنغ", departmentId: "dept_media", level: 4 },
  { id: "pos_cleaner", code: "CLN", name: "Cleaner", nameAr: "تنظيف", departmentId: "dept_services", level: 1 },
];

// ==================== الموظفين ====================
export const EMPLOYEES = [
  {
    id: "emp_hassan",
    employeeCode: "BI-000",
    fullName: "حسن فؤاد حمزه عبد",
    email: "hassan@bi.local",
    phone: "07715473797",
    positionId: "pos_owner",
    departmentId: null,
    role: "المالك / المدير المفوض",
    hireDate: "2024-06-20",
    salary: 0,
    workStartTime: "مرن",
    workEndTime: "مرن",
    emergencyContact: "أحمد فؤاد حمزه",
    emergencyPhone: "07810109922",
    isOwner: true,
  },
  {
    id: "emp_mohammad_raed",
    employeeCode: "BI-001",
    fullName: "محمد رائد سبوس الكناني",
    email: "mohammad.raed@bi.local",
    phone: "07713207274",
    positionId: "pos_installer",
    departmentId: "dept_preparation",
    role: "تنصيب وتجهيز الحاسبات والبرامج",
    hireDate: "2025-10-12",
    salary: 500000,
    bonus: 100000,
    workStartTime: "13:00",
    workEndTime: "23:00",
    emergencyContact: "علي سليم كريم",
    emergencyPhone: "+9647707100887",
  },
  {
    id: "emp_mohammad_hassan",
    employeeCode: "BI-002",
    fullName: "محمد حسن عبد الحمزة يوسف حسين",
    email: "mohammad.hassan@bi.local",
    phone: "078340155134",
    positionId: "pos_prep",
    departmentId: "dept_preparation",
    role: "مجهز لابتوبات",
    hireDate: "2025-10-25",
    salary: 500000,
    bonus: 100000,
    workStartTime: "مرن",
    workEndTime: "مرن",
    emergencyContact: "خالد عبد الحمزة يوسف",
    emergencyPhone: "07822025275",
  },
  {
    id: "emp_abdullah_firas",
    employeeCode: "BI-003",
    fullName: "عبدالله فراس عبدالرحيم راضي الكرعاوي",
    email: "abdullah.firas@bi.local",
    phone: null,
    positionId: "pos_tech_support",
    departmentId: "dept_support",
    role: "موظف دعم فني وتنصيب البرامج للزبائن أونلاين",
    hireDate: "2025-10-01",
    salary: 500000,
    bonus: 100000,
    workStartTime: "14:00",
    workEndTime: "00:00",
  },
  {
    id: "emp_yaser",
    employeeCode: "BI-004",
    fullName: "ياسر حسين علي عبد الحسناوي",
    email: "yaser@bi.local",
    phone: "07819131328",
    positionId: "pos_maintenance",
    departmentId: "dept_maintenance",
    role: "فحص لابتوبات + استلام الأجهزة المعيوبة",
    hireDate: "2025-04-03",
    salary: 600000,
    workStartTime: "09:00",
    workEndTime: "19:00",
    emergencyContact: "ناصر حسين",
    emergencyPhone: "+9647729669957",
  },
  {
    id: "emp_osama",
    employeeCode: "BI-005",
    fullName: "أسامة رائد صيهود عطشان القيسي",
    email: "osama@bi.local",
    phone: "07700895638",
    positionId: "pos_prep",
    departmentId: "dept_preparation",
    role: "التجهيز",
    hireDate: "2025-10-26",
    salary: 500000,
    bonus: 100000,
    workStartTime: "مسائي",
    workEndTime: null,
    emergencyContact: "رائد صيهود",
    emergencyPhone: "07715011174",
  },
  {
    id: "emp_mohammad_ali",
    employeeCode: "BI-006",
    fullName: "محمد علي عباس حميد علوش",
    email: "mohammad.ali@bi.local",
    phone: "07827819726",
    positionId: "pos_photographer",
    departmentId: "dept_media",
    role: "مصور الشركة",
    hireDate: null,
    salary: 600000,
    workStartTime: "مسائي",
    workEndTime: null,
    emergencyContact: "جعفر علي عباس",
    emergencyPhone: "07803314954",
  },
  {
    id: "emp_youssef",
    employeeCode: "BI-007",
    fullName: "يوسف عبد الرزاق ناجي رزوقي",
    email: "youssef@bi.local",
    phone: "07808022359",
    positionId: "pos_editor",
    departmentId: "dept_media",
    role: "مونتير / قسم الإعلام",
    hireDate: null,
    salary: 750000,
    workStartTime: "مرن",
    workEndTime: null,
    workLocation: "من البيت",
    emergencyContact: "رزاق ناجي",
    emergencyPhone: "07831009371",
  },
  {
    id: "emp_taher",
    employeeCode: "BI-008",
    fullName: "طاهر عباس عيسى",
    email: "taher@bi.local",
    phone: "07826941585",
    positionId: "pos_programmer",
    departmentId: "dept_programming",
    role: "مبرمج - نظام ERP",
    hireDate: null,
    salary: 1200000,
    workStartTime: "مرن",
    workEndTime: null,
    workType: "أونلاين + زيارة أسبوعية",
    emergencyContact: "ماهر عباس عيسى",
    emergencyPhone: "+964 780 705 4800",
  },
  {
    id: "emp_sukar",
    employeeCode: "BI-009",
    fullName: "سكر صفاء سكر لفتة",
    email: "sukar@bi.local",
    phone: "07815632925",
    positionId: "pos_sales",
    departmentId: "dept_sales",
    role: "خدمة زبائن / مبيعات",
    hireDate: null,
    salary: 1000000,
    workStartTime: "مرن",
    workEndTime: null,
    rating: 10,
    emergencyContact: "صفاء",
    emergencyPhone: "07805465857",
  },
  {
    id: "emp_haider",
    employeeCode: "BI-010",
    fullName: "حيدر رزاق عبد الواحد",
    email: "haider@bi.local",
    phone: "07838844400",
    positionId: "pos_programmer",
    departmentId: "dept_programming",
    role: "مبرمج",
    hireDate: null,
    salary: 800000,
    workStartTime: "مرن",
    workEndTime: null,
    emergencyContact: "علي",
    emergencyPhone: "07815795980",
  },
  {
    id: "emp_abdullah_haider",
    employeeCode: "BI-011",
    fullName: "عبدالله حيدر كاظم محمد",
    email: "abdullah.haider@bi.local",
    phone: "07849654259",
    positionId: "pos_cleaner",
    departmentId: "dept_services",
    role: "تنظيف",
    hireDate: null,
    salary: 400000,
    workStartTime: "صباحي",
    workEndTime: null,
    emergencyContact: "حيدر",
    emergencyPhone: "07840206415",
  },
  {
    id: "emp_ali_mahmoud",
    employeeCode: "BI-012",
    fullName: "علي محمود علي رستم",
    email: "ali.mahmoud@bi.local",
    phone: "07717455069",
    positionId: "pos_marketing",
    departmentId: "dept_media",
    role: "مسؤول ماركتنغ / إدارة السوشيال ميديا",
    hireDate: null,
    salary: 300000,
    workType: "عن بعد (Remote)",
    workStartTime: "مرن",
    workEndTime: null,
    workLocation: "بغداد",
  },
  {
    id: "emp_mojtaba",
    employeeCode: "BI-013",
    fullName: "مجتبى حسين جعفر هاشم",
    nickname: "دكتور مجتبى",
    email: "mojtaba@bi.local",
    phone: "07838299803",
    positionId: "pos_designer",
    departmentId: "dept_design",
    role: "مصمم جرافيك - فوتوشوب",
    hireDate: null,
    salary: 500000,
    workStartTime: "مرن",
    workEndTime: null,
    emergencyContact: "حيدر",
    emergencyPhone: "07765957872",
  },
];

// ==================== معلومات الشركة ====================
export const COMPANY_INFO = {
  id: "company_bi",
  name: "BI للحاسبات",
  fullName: "Beyond Intelligence",
  abbreviation: "BI",
  type: "مكتب حاسبات",
  establishmentDate: "2024-06-20",
  owner: "حسن فؤاد",
  location: "بابل - الأكرمين",
  phone: "07715473797",
  instagram: "https://www.instagram.com/bi_iraq1",
  facebook: "https://www.facebook.com/share/1KMbW8mLLb/",
  totalEmployees: 14,
  warranties: {
    stickerWarranty: {
      name: "ضمان ملصق BI",
      duration: "مدى الحياة",
      includes: ["فورمات مجاني مدى الحياة", "تنصيب جميع البرامج مجاناً مدى الحياة", "صيانة يدوية مجاناً مدى الحياة"],
    },
    receiptWarranty: {
      name: "ضمان الوصل",
      duration: "7 أيام",
      includes: ["استبدال الجهاز فوراً في حال وجود أي خلل"],
    },
  },
};
